// Generated by CoffeeScript 1.9.1
var connect, port, server;

connect = require('connect');

server = connect();

server.use(connect['static'](__dirname + "/../static"));

port = 5000;

server.listen(port, function() {
  return console.log("Listening on " + port);
});
